another commit

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -4,7 +4,9 @@ git status
 while true; do
     read -p "Do you want to deploy these changes??" yn
     case $yn in
-        [Yy]* ) git add *; git commit -m "another commit"; git push origin master;  break;;
+        [Yy]* ) git add *; git commit -m "another commit"; git push origin master;  if [ $? != 0 ] ; then
+    echo "Git failed. Need new key"
+fi; break;;
         [Nn]* ) exit;;
         * ) echo "Please answer yes or no.";;
     esac
